# TASK(21-06-2021)
- Create arrays with all the data types Available in numpy
- Numpy has 11 Datatypes and the characters used to represent them are:
    - integer - i
    - boolean - ?
    - unsigned integer - u
    - float - f
    - complex float - c
    - timedelta - m
    - datetime - M
    - object - O
    - string - S
    - unicode string - U
    - fixed chunk of memory for other type (void) - V

## Int Datatype

In [1]:
# Creating array with integer in numpy

import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(a.dtype)

[1 2 3 4 5]
int32


In [2]:
import numpy as np
a = np.array([-1,2,3,-4,5],dtype = 'intc')  ## int
print(a)
print(a.dtype)

[-1  2  3 -4  5]
int32


In [3]:
import numpy as np
a = np.array([1,2,3,4,5],dtype = 'int_')  ## long
print(a)
print(a.dtype)

[1 2 3 4 5]
int32


In [4]:
import numpy as np
a = np.array([-1,2,3,4,5],dtype = 'longlong')
print(a)
print(a.dtype)

[-1  2  3  4  5]
int64


## boolean Datatype

In [5]:
# Creating array with boolean in numpy
import numpy as np
a = np.array([0,1,2,3,4,5],dtype = '?')
print(a)
print(a.dtype)

[False  True  True  True  True  True]
bool


In [6]:
import numpy as np
a = np.array([1,2,3,4], dtype='bool_')
print(a)
print(a.dtype)

[ True  True  True  True]
bool


## Unsigned Datatype

In [7]:
# Creating array with unsigned integer in numpy

import numpy as np
a = np.array([0,-1,2,-3,4,5],dtype = 'uint')   ## unsigned long
print(a)
print(a.dtype)

[         0 4294967295          2 4294967293          4          5]
uint32


In [8]:
import numpy as np
a = np.array([-1,2,3,-4,5],dtype = 'uintc')  ## unsigned int
print(a)
print(a.dtype)

[4294967295          2          3 4294967292          5]
uint32


In [9]:
import numpy as np
a = np.array([0,-1,2,-3,4,5],dtype = 'uint8')
print(a)
print(a.dtype)

[  0 255   2 253   4   5]
uint8


In [10]:
import numpy as np
a = np.array([0,-1,2,-3,4,5],dtype = 'uint16')
print(a)
print(a.dtype)


[    0 65535     2 65533     4     5]
uint16


In [11]:
import numpy as np
a = np.array([0,-1,2,-3,4,5],dtype = 'uint32')
print(a)
print(a.dtype)

[         0 4294967295          2 4294967293          4          5]
uint32


In [12]:
import numpy as np
a = np.array([0,-1,2,-3,4,5],dtype = 'uint64')
print(a)
print(a.dtype)

[                   0 18446744073709551615                    2
 18446744073709551613                    4                    5]
uint64


In [13]:
import numpy as np
a = np.array([-1,2,3,4,5],dtype = 'ulonglong')
print(a)
print(a.dtype)

[18446744073709551615                    2                    3
                    4                    5]
uint64


## Float DataType

In [14]:
# Creating array with float in numpy
a = np.array([1.23,2.3,4,4.5,5])
print(a)
print(a.dtype)

[1.23 2.3  4.   4.5  5.  ]
float64


In [15]:
import numpy as np
a = np.array([1,2,3,4], dtype='f')
print(a)
print(a.dtype)

[1. 2. 3. 4.]
float32


In [16]:
import numpy as np
a = np.array([1,2,3,4], dtype='half')
print(a)
print(a.dtype)

[1. 2. 3. 4.]
float16


In [17]:
import numpy as np
a = np.array([1,2,3,4], dtype='single')
print(a)
print(a.dtype)

[1. 2. 3. 4.]
float32


In [18]:
import numpy as np
a = np.array([1,2,3,4], dtype='double')
print(a)
print(a.dtype)

[1. 2. 3. 4.]
float64


In [19]:
import numpy as np
a = np.array([1,2,3,4], dtype='longdouble')
print(a)
print(a.dtype)

[1. 2. 3. 4.]
float64


## Complex float DataType

In [20]:
# Creating array with complex float in numpy
a = np.array([1.23+1j,2.3+2j,4,4.5,5+4j])
print(a)
print(a.dtype)

[1.23+1.j 2.3 +2.j 4.  +0.j 4.5 +0.j 5.  +4.j]
complex128


In [21]:
import numpy as np
a = np.array([1,2,3,4], dtype='csingle')
print(a)
print(a.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex64


In [22]:
import numpy as np
a = np.array([1,2,3,4], dtype='cdouble')
print(a)
print(a.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


In [23]:
import numpy as np
a = np.array([1,2,3,4], dtype='clongdouble')
print(a)
print(a.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


## Timedelta DataType

In [24]:
# Creating array with Timedelta in numpy
a = np.timedelta64(12, 'M')
print(a)
print(a.dtype)

12 months
timedelta64[M]


In [25]:
a = np.timedelta64(12, 'D')
print(a)
print(a.dtype)

12 days
timedelta64[D]


In [26]:
a = np.timedelta64(12, 'W')
print(a)
print(a.dtype)

12 weeks
timedelta64[W]


## datetime DataType

In [27]:
# Creating array with datetime in numpy
a = np.array(['2010-07-11', '2006-01-13'])
print(a)
print(a.dtype)

['2010-07-11' '2006-01-13']
<U10


In [28]:
a = np.array(['2010-07-11', '2006-01-13','2001-12-23'],dtype='datetime64')
print(a)
print(a.dtype)

['2010-07-11' '2006-01-13' '2001-12-23']
datetime64[D]


In [29]:
import numpy as np
a = np.array(['2010-07-11', '2006-01-13', '2010-08-13'], dtype='M')
print(a)
print(a.dtype)

['2010-07-11' '2006-01-13' '2010-08-13']
datetime64[D]


## Object Datatype

In [31]:
# Creating array with Object in numpy

import numpy as np
a = np.array(['vamsi',2,3,4], dtype='O')
print(a)
print(a.dtype)

['vamsi' 2 3 4]
object


## String Datatype

In [32]:
# Creating array with String in numpy

import numpy as np
a = np.array([1,2,3,4], dtype='S')
print(a)
print(a.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [33]:
a = np.array(['vamsi', 'Harshith', 'Datta', 'ch'])
print(a)
print(a.dtype)

['vamsi' 'Harshith' 'Datta' 'ch']
<U8


## Unicode string DataType

In [34]:
## creating array with unicode in array:
a = np.array([u'\u0065', u'\u0123', u'\265F', u'\u2202r'])
print(a)
print(a.dtype)

['e' 'ģ' 'µF' '∂r']
<U2


In [35]:
import numpy as np
a = np.array([u'\u0394', u'\265E', u'\265F', u'\u2202r'], dtype='U')
print(a)
print(a.dtype)

['Δ' 'µE' 'µF' '∂r']
<U2
